server:
  port: 8085

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgres://localhost:5432/soa
    username: postgres
    password: 20102003
  application:
    name: attendance-service

  #----------------------------------------------------------------------------------------------------------------------#


